using Pkg
Pkg.add("Colors")
Pkg.add("ColorSchemes")
Pkg.add("NearestNeighbors")
Pkg.add("GeoStats")
Pkg.add("Images")
Pkg.add("Clustering")
Pkg.add("GeoJSON")
Pkg.add("Distances")
Pkg.add("LibGEOS")
Pkg.add("ArgParse")
Pkg.add("Compat")
Pkg.add("Nullables")
# Pkg.add("Lumberjack")
Pkg.add("SortingAlgorithms")
Pkg.add("ProgressMeter")
Pkg.add("DataArrays")
Pkg.add("Glob")
Pkg.add("LasIO")
Pkg.add("GDAL")
Pkg.add("TiledIteration")
Pkg.add("JSON")
Pkg.add("FixedPointNumbers")
